#!/usr/bin/env node
/**
 * Reads words/wordle-answers.txt and words/wordle-valid.txt, then writes
 * src/lib/words.gen.mjs exporting:
 *   ANSWERS — curated answer pool
 *   WORDS   — all valid guesses (answers ∪ valid-only), for guess validation
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

function loadLines(file) {
  return readFileSync(join(root, file), 'utf-8')
    .split('\n')
    .map(w => w.trim().toLowerCase())
    .filter(w => w.length === 5 && /^[a-z]+$/.test(w));
}

const answers = [...new Set(loadLines('words/wordle-answers.txt'))].sort();
const words   = [...new Set([...answers, ...loadLines('words/wordle-valid.txt')])].sort();

function formatArray(name, arr) {
  const PER_LINE = 8;
  const rows = [];
  for (let i = 0; i < arr.length; i += PER_LINE) {
    rows.push('  ' + arr.slice(i, i + PER_LINE).map(w => `'${w}'`).join(', '));
  }
  return `export const ${name} = [\n${rows.join(',\n')},\n];`;
}

const out = [
  '// Generated by scripts/generate-words.mjs — do not edit manually.',
  formatArray('ANSWERS', answers),
  formatArray('WORDS', words),
].join('\n\n') + '\n';

const outPath = join(root, 'src', 'lib', 'words.gen.mjs');
writeFileSync(outPath, out, 'utf-8');
console.log(`ANSWERS: ${answers.length}  WORDS: ${words.length}  → ${outPath}`);
